file_format: "1"
id: Synth Wave
name: Synth Wave
type: shield
url: https://github.com/luerl21/synth-wave
requires:
    # - seeed_xiao
    # - nice_view
features:
    - keys
    # - display
siblings:
    - synth-wave-left
    - synth-wave-right