file_format: "1"
id: Synth Wave
name: Synth Wave
type: shield
url: https://github.com/luerl21/synth_wave
requires:
  - pro_micro
features:
    - keys
siblings:
    - synth_wave_left
    - synth_wave_right