file_format: "1"
id: Synth Wave
name: Synth Wave
type: shield
url: https://github.com/luerl21/synth_wave
requires:
    # - seeed_xiao
    # - nice_view
features:
    - keys
    # - display
siblings:
    - synth_wave_left
    - synth_wave_right